### PR TITLE
Fixed `gulp build:production` does not generate unminified/unoptimized CSS/JS files.

### PR DESCRIPTION
**Pull request by sun**
Repeats #3 after it was reverted in https://github.com/netzstrategen/gulp-task-collection/commit/5895511664099096b2b5b61b89791d311cc7c81a

Problem
* When running `gulp build` to set up a new instance of an existing project (e.g. during a deployment process), then only minified/optimized files are generated, causing 404 errors and a broken front-end in case the application searches for unminified files.

Goal
* Simplify project setup and deployment processes.

Proposed solution
1. Always write out the generated unminified/unoptimized files before the content is (potentially) minified/optimized.
    * As visible in the diff, the precompiled but yet unminified/unoptimized files are available right there and can be written out to disk with zero additional cost.

Notes
* Having the unminified files in production is not a problem; they're simply not used.

* For `production: false` this PR causes a double write to the same file, which may be optimized in the future, but does not present a problem right now.

Details
* Generating the unmodified/unoptimized files takes twice the time for the case of `build:production` even though the necessary output was generated already.
* It doesn't appear to be possible to run `build` and `build:production` in sequence, because both invoke `clean` as first operation.
* Running tasks after each other compiles the files separately from scratch for each task.  That is a waste of time and resources.

### CODE REVIEW

**Comment by colourgarden** [comment]
Is this change still relevant? What project do we need it for?

Previous Slack discussion [here](https://netzstrategen.slack.com/archives/C9Y7CQUPL/p1534974992000100).

**Comment by sun** [comment]
Yes, it's still relevant when using gulp-task-collection in an application that allows to switch asset file loading between minified/optimized and original source files through a configuration setting, such as the `SCRIPT_DEBUG` constant in WordPress and similar settings in other systems.

**Comment by sun** [comment]
Unoptimized source files obviously cannot be loaded from assets, as they are not yet compiled in there.

**Comment by sun** [comment]
This is still needed to properly handle e.g. the SCRIPT_DEBUG constant in WordPress. The constant can be flipped at any time and the site should still load correctly when plugins and themes are requesting the minified or non-minified assets.

We've started to conditionally load separate files in some projects depending on the constant already, but some of the projects are now trying to load the files from the uncompiled assets folder, which obviously cannot work if they contain e.g. SCSS instead of CSS files.

A separate, non-standard build task does not make sense from my perspective, as these files should be generated by default during the regular compilation.  Writing out the intermediate files before they get optimized and minified is the most sensible solution, which also does not negatively affect the build time.

**Comment by wrux** [comment]
Closing this in favour of #33

**Pull request closed without merging**
