### PR TITLE
Added ESLint to scripts task.

### PR DESCRIPTION
**Pull request by LucaPipolo**

### CODE REVIEW

**Comment by colourgarden** [comment]
@LucaPipolo Looks like we're missing the config file - `No ESLint configuration found`.

I guess we don't need to set anything custom (just use ESLint defaults) but we probably need a config file in the repo to avoid this error showing? Which also raises the question of it we should add the `.stylelintrc` file to this repo also? Maybe `.stylelintrc-sample` and `.eslintrc-sample`?

**Comment by LucaPipolo** [comment]
@colourgarden — yup, I intentionally did not commit the ESLint config file because I saw also the Stylelint one was missing.

Honestly, I'm not convinced we should add them to this repo. IMHO linter configuration files should be really part of the project in which this package is used.

It also looks good to me that Gulp complains about the missing of the ESLint config file so that the user know he had to create one into the project to let it work.

The only thing I'd do is to specify it into the README file and make it clear that linters config files are not included and need to be created.

**Comment by colourgarden** [comment]
@LucaPipolo Then we should maybe create a repo with our default config files? Could also add editor config files there too for new hires.

But I do still need a config file to be able to test this branch so please send me one on Slack 😂

**Comment by LucaPipolo** [comment]
@colourgarden — so can we merge it or…? :)

**Pull request merged**
